Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "auf-liferay" do |config|
    config.vm.network :forwarded_port, guest: 8080, host: 8080
    config.vm.network :forwarded_port, guest: 8000, host: 8000
    config.vm.network :private_network, ip: "10.0.0.17"
    
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
    end
    
    
    config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "default.pp"
    end
  end

#  config.vm.host_name = "auf-intranet"

#  config.vm.forward_port 8080, 8080
#  config.vm.forward_port 8000, 8000
#  config.vm.customize ["modifyvm", :id, "--memory", 1024]

#  config.vm.network :hostonly, "10.0.0.10"

end
